python3 run_ocr.py > ../tmp/ocr_ret01.txt
python3 run_ocr.py > ../tmp/ocr_ret02.txt
python3 run_ocr.py > ../tmp/ocr_ret03.txt
python3 run_ocr.py > ../tmp/ocr_ret04.txt
python3 run_ocr.py > ../tmp/ocr_ret05.txt
python3 run_ocr.py > ../tmp/ocr_ret06.txt
python3 run_ocr.py > ../tmp/ocr_ret07.txt
python3 run_ocr.py > ../tmp/ocr_ret08.txt
python3 run_ocr.py > ../tmp/ocr_ret09.txt

python3 run_ocr.py > ../tmp/ocr_ret10.txt
python3 run_ocr.py > ../tmp/ocr_ret11.txt
python3 run_ocr.py > ../tmp/ocr_ret12.txt
python3 run_ocr.py > ../tmp/ocr_ret13.txt
python3 run_ocr.py > ../tmp/ocr_ret14.txt
python3 run_ocr.py > ../tmp/ocr_ret15.txt
python3 run_ocr.py > ../tmp/ocr_ret16.txt
python3 run_ocr.py > ../tmp/ocr_ret17.txt
python3 run_ocr.py > ../tmp/ocr_ret18.txt
python3 run_ocr.py > ../tmp/ocr_ret19.txt

python3 run_ocr.py > ../tmp/ocr_ret20.txt
python3 run_ocr.py > ../tmp/ocr_ret21.txt
python3 run_ocr.py > ../tmp/ocr_ret22.txt
python3 run_ocr.py > ../tmp/ocr_ret23.txt
python3 run_ocr.py > ../tmp/ocr_ret24.txt
python3 run_ocr.py > ../tmp/ocr_ret25.txt
python3 run_ocr.py > ../tmp/ocr_ret26.txt
python3 run_ocr.py > ../tmp/ocr_ret27.txt
python3 run_ocr.py > ../tmp/ocr_ret28.txt
python3 run_ocr.py > ../tmp/ocr_ret29.txt

python3 run_ocr.py > ../tmp/ocr_ret30.txt
python3 run_ocr.py > ../tmp/ocr_ret31.txt
python3 run_ocr.py > ../tmp/ocr_ret32.txt
python3 run_ocr.py > ../tmp/ocr_ret33.txt
python3 run_ocr.py > ../tmp/ocr_ret34.txt
python3 run_ocr.py > ../tmp/ocr_ret35.txt
python3 run_ocr.py > ../tmp/ocr_ret36.txt
python3 run_ocr.py > ../tmp/ocr_ret37.txt
python3 run_ocr.py > ../tmp/ocr_ret38.txt
python3 run_ocr.py > ../tmp/ocr_ret39.txt

python3 run_ocr.py > ../tmp/ocr_ret40.txt
python3 run_ocr.py > ../tmp/ocr_ret41.txt
python3 run_ocr.py > ../tmp/ocr_ret42.txt
python3 run_ocr.py > ../tmp/ocr_ret43.txt
python3 run_ocr.py > ../tmp/ocr_ret44.txt
python3 run_ocr.py > ../tmp/ocr_ret45.txt
python3 run_ocr.py > ../tmp/ocr_ret46.txt
python3 run_ocr.py > ../tmp/ocr_ret47.txt
python3 run_ocr.py > ../tmp/ocr_ret48.txt
python3 run_ocr.py > ../tmp/ocr_ret49.txt

python3 run_ocr.py > ../tmp/ocr_ret50.txt
python3 run_ocr.py > ../tmp/ocr_ret51.txt
python3 run_ocr.py > ../tmp/ocr_ret52.txt
python3 run_ocr.py > ../tmp/ocr_ret53.txt
python3 run_ocr.py > ../tmp/ocr_ret54.txt
python3 run_ocr.py > ../tmp/ocr_ret55.txt
python3 run_ocr.py > ../tmp/ocr_ret56.txt
python3 run_ocr.py > ../tmp/ocr_ret57.txt
python3 run_ocr.py > ../tmp/ocr_ret58.txt
python3 run_ocr.py > ../tmp/ocr_ret59.txt

python3 run_ocr.py > ../tmp/ocr_ret60.txt
python3 run_ocr.py > ../tmp/ocr_ret61.txt
python3 run_ocr.py > ../tmp/ocr_ret62.txt
python3 run_ocr.py > ../tmp/ocr_ret63.txt
python3 run_ocr.py > ../tmp/ocr_ret64.txt
python3 run_ocr.py > ../tmp/ocr_ret65.txt
python3 run_ocr.py > ../tmp/ocr_ret66.txt
python3 run_ocr.py > ../tmp/ocr_ret67.txt
python3 run_ocr.py > ../tmp/ocr_ret68.txt
python3 run_ocr.py > ../tmp/ocr_ret69.txt